### ISSUE TITLE
Allow use of ngx-meta in angular 8 project

### ISSUE THREAD

**Issue by mthomasson** [fulls1z3/ngx-meta#193]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Feature request
[ ] Documentation issue or request
```

**Current behavior**
Using the current version generates warnings in the console:
```
warning " > @ngx-meta/core@7.0.0" has incorrect peer dependency "@angular/core@>=7.0.0 <8.0.0".
warning " > @ngx-meta/core@7.0.0" has incorrect peer dependency "@angular/platform-browser@>=7.0.0 <8.0.0".
warning " > @ngx-meta/core@7.0.0" has incorrect peer dependency "@angular/platform-browser-dynamic@>=7.0.0 <8.0.0".
warning " > @ngx-meta/core@7.0.0" has incorrect peer dependency "@angular/router@>=7.0.0 <8.0.0".
```
**Expected/desired behavior**
Have a version tha points toward angular 8

**Minimal reproduction of the problem with instructions**

**What is the motivation/use case for changing the behavior?**
Want to upgrade an Angular 7 project to Angular 8.
**Environment**
* **Angular version:** 8.1.2

* **Browser:**
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX

* **For Tooling issues:**
- Node version: XX  
- Platform:  

* Others:

**Comment by rafa-suagu** [comment]
some news @fulls1z3 ?

**Comment by bjornharvold** [comment]
Yes please

**Comment by fulls1z3** [comment]
done
