### ISSUE TITLE
set meta tags thru `MetaGuard`

### ISSUE THREAD

**Issue by fulls1z3** [fulls1z3/ngx-meta#35]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[X] feature request
```

**Current behavior**
As of [1ff82a2](https://github.com/nglibs/meta/commit/1ff82a2fcf4a8278f8951ab0932a1a44ad7543e8), @nglibs/meta works both on client and server platforms. Also, the meta tags generated by @nglibs/meta are fully SEO-friendly (visible on the HTML source). However, the meta tags are not fully visible using a callback function (ex: ngx-translate).

**Expected/desired behavior**
We must provide **full** SEO-friendliness on meta tags. The following steps will maintain the desired functionality:

- [X] Abandon traversing routes to seek meta information
- [X] Introduce a generic route guard (`MetaGuard`)
- [X] ~~Append route guards to route configuration dynamically (fails angular-cli due to [#15305](https://github.com/angular/angular/issues/15305), [#4541](https://github.com/angular/angular-cli/issues/4541))~~
- [x] Provide documentation for the use of `MetaGuard`

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =
